### ISSUE TITLE
Build for Python 3.12

### ISSUE THREAD

**Issue by niccokunzmann** [dominickpastore/pymd4c#34]
My installation is failing at the moment because I use Python 3.12.

```
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [52 lines of output]
      running dist_info
      creating /tmp/pip-modern-metadata-v08089r8/pymd4c.egg-info
      writing /tmp/pip-modern-metadata-v08089r8/pymd4c.egg-info/PKG-INFO
      writing dependency_links to /tmp/pip-modern-metadata-v08089r8/pymd4c.egg-info/dependency_links.txt
      writing requirements to /tmp/pip-modern-metadata-v08089r8/pymd4c.egg-info/requires.txt
      Traceback (most recent call last):
        File "/home/nicco/open-web-calendar/.tox/docs/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/nicco/open-web-calendar/.tox/docs/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/nicco/open-web-calendar/.tox/docs/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-xfp74w9u/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 366, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/tmp/pip-build-env-xfp74w9u/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 487, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-xfp74w9u/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 117, in <module>
        File "/tmp/pip-build-env-xfp74w9u/overlay/lib/python3.12/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-xfp74w9u/overlay/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 184, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-xfp74w9u/overlay/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-xfp74w9u/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-xfp74w9u/overlay/lib/python3.12/site-packages/setuptools/dist.py", line 968, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-xfp74w9u/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-xfp74w9u/overlay/lib/python3.12/site-packages/setuptools/command/dist_info.py", line 92, in run
          self.egg_info.run()
        File "/tmp/pip-build-env-xfp74w9u/overlay/lib/python3.12/site-packages/setuptools/command/egg_info.py", line 314, in run
          writer(self, ep.name, os.path.join(self.egg_info, ep.name))
        File "/tmp/pip-build-env-xfp74w9u/overlay/lib/python3.12/site-packages/setuptools/command/egg_info.py", line 702, in write_toplevel_names
          pkgs = dict.fromkeys([
                               ^
        File "/tmp/pip-build-env-xfp74w9u/overlay/lib/python3.12/site-packages/setuptools/dist.py", line 926, in iter_distribution_names
          for ext in self.ext_modules or ():
        File "<string>", line 61, in __iter__
        File "<string>", line 55, in _fetch_pkgconfig_all
        File "<string>", line 38, in _fetch_pkgconfig
        File "/tmp/pip-build-env-xfp74w9u/normal/lib/python3.12/site-packages/pkgconfig/pkgconfig.py", line 248, in parse
          _raise_if_not_exists(package)
        File "/tmp/pip-build-env-xfp74w9u/normal/lib/python3.12/site-packages/pkgconfig/pkgconfig.py", line 103, in _raise_if_not_exists
          raise PackageNotFoundError(package)
      pkgconfig.pkgconfig.PackageNotFoundError: md4c not found
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
```

The build from source fails. I wonder: Can the wheels be built for this in Python 3.12 and uploaded?
Context: Ubuntu released an upgrade to OS which uses 3.12 by default now.

**Comment by dingyifei** [comment]
I have similar issue, where mine was fixed by installing libmd4c `sudo apt-get install libmd4c-html0 libmd4c-html0-dev libmd4c-dev`
